//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace erp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class sys_user
    {
        public int id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public bool emailConfirm { get; set; }
        public string phoneNumber { get; set; }
        public System.DateTime dateRegistry { get; set; }
        public bool accessFailedCount { get; set; }
        public System.DateTime lastLogged { get; set; }
        public Nullable<int> userRoleID { get; set; }

        [NotMapped]
        public List<sys_user> UserDD { get; set; }
    }
}
